### PR TITLE
Perl Version detection & Advanced Services with Hostgroup issue

### PR DESCRIPTION
**Pull request by jvogt-swp**
see commit messages and https://github.com/nconf/development/issues/1

### CODE REVIEW

**Comment by jvogt-swp** [comment]
When creating an advanced services linked to a hostgroup which itself does not have any direct members does not work. The setup is as follows:

Advanced Service (Antivirus) <- Hostgroup (Windows) <- Hostgroups (Windows 2K, Windows 2K3, ... ) <- Members (Server1, Server2)

During config file creation Hostgroup Windows is detected as not present on collector and removed.

**Comment by gargiulo** [comment]
Hi. Thank you for the fixes! I have applied them to our code. 
I was trying to verify if the same issue exists with chained servicegroups, but it seems servicegroups don't have that issue since they are treated differently.

**Comment by gargiulo** [comment]
Could you unfork your nconf branch if you don't have any other changes?

**Comment by jvogt-swp** [comment]
I do have another change which is not yet ready.

It is a new authorisation scheme but it's not yet done. Basically letting the webserver do the authentication and just creating users in case they don't exist yet as contacts and add them to a contact group.

-----Ursprüngliche Nachricht-----
Von: Angelo Gargiulo [mailto:reply@reply.github.com] 
Gesendet: Mittwoch, 14. September 2011 09:30
An: Vogt, Jonathan
Betreff: Re: [development] Perl Version detection & Advanced Services with Hostgroup issue (#2)

Could you unfork your nconf branch if you don't have any other changes?

##

**Pull request merged**
