### PR TITLE
JSON format error

### PR DESCRIPTION
**Pull request by Tontonitch**
JSON format error

The problem was with the backslash. And this is quite common to have such a character in the action_URL string.

Discovered that some backslashes don't have to be doubled. So the patch above breaks some other strings.
ex:
    "<a href=\"detail.php?id=7054\">Cisco_environment</a>",
Corrected the patch (more accurate to \' pattern):

BR,
Yannick

Related forum topic:
http://forum.nconf.org/viewtopic.php?f=18&t=869

### CODE REVIEW

**Comment by Tontonitch** [comment]
The string replacement I proposed is okay for me. Doubling the backslash is what I wanted for some particular situations at least. That resolved any JSON format problem on my setup. Do you face some problem with the double backslashes?

I will try your string replacement next week.

Br,
Yannick

**Comment by Cyclodex** [comment]
No problems, but there are shown to many of them then, so I am guessing this is the wrong approach, looks like the problem is simpler, like my replacement. Just remove the backslash before the quote, because that seems to be to much.
Yea, would be nice if you can test my changes, for the other related links. not sure how or where you put that.

**Comment by Tontonitch** [comment]
I did a test of your string replacement on my setup.
I didn't discover any JSON format problem since now. And indeed, your solution seems to be the easiest but best one, which should avoid any problem with backslashes+quote.

**Comment by Cyclodex** [comment]
Hey Tontonitch, can you please try out my updates which I have just commited, I implemented a new solution with fallback to this one in my previous comment.
check this one: https://github.com/nconf/development/commit/c3a47849bc90a1dcad0d0b382684befc22a7a69f
thanks for feedback! If ok I will merge this back into the master!

**Pull request closed without merging**
